apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-weatherapp
spec:
  selector:
    matchLabels:
      app: golang-weatherapp
  template:
    metadata:
      labels:
        app: golang-weatherapp
    spec:
      containers:
      - name: golang-weatherapp
        image: quay.io/omidiyanto/golang-weatherapp:latest
        env:
        - name: GOOGLE_CLIENT_ID
          value: "..."
        - name: GOOGLE_CLIENT_SECRET
          value: "..."
        - name: OPENWEATHER_API_KEY
          value: "..."
        - name: REDIRECT_URI
          value: "..."
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
